name: Deployme

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.DEPLOYME_PRIVATE_SSH_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.DEPLOYME_HOST}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
